apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pwa-apps-hpa-cpu
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pwa-apps
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 30
